version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: pg-local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reembolso
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
