quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
      driver: org.h2.Driver
    username: sa
    password: sa

  hibernate-orm:
    schema-management:
      strategy: drop-and-create
      create-schemas: true
    sql-load-script: no-file
  oidc:
    # URL do User Pool (issuer)
    auth-server-url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_UdO9SF2dY
    # Client ID e secret do App client Cognito
    client-id: 2cdjagd9aavp7f45n7is71ntvn
    credentials:
      secret: 1n6r3me4ldar0j43t8bsds0bhpg204te0j6totoakfde0l65tgv9
    # Tipo de aplicação (fluxo web)
    application-type: web-app
    authorization-path: /oauth2/authorization
    authentication:
      redirect-path: /callback
    # Audience esperado no token ID
    token:
      audience: 2cdjagd9aavp7f45n7is71ntvn
    # Mapeia grupos Cognito para @RolesAllowed
    roles:
      source: accesstoken
      claim: cognito:groups

  http:
    cors:
      origins: "http://localhost:5173"
      methods: GET,POST,PUT,DELETE